### ISSUE TITLE
Minor arithmetic compiler warning

### ISSUE THREAD

**Issue by FrancoisCarouge** [cvra/pid#19]
Hello,
I am playing around with this cool project, and firstly want to say thank you.
Also I would like to report a compiler warning which should be handled gracefully:

pid-master\pid.c(11): warning C4756: overflow in constant arithmetic

The compiler used is MSVC 2015 with the CTP November 2013 tool chain.

Best,
François

**Comment by antoinealb** [comment]
Hi Francois,
Glad to see our implementation being useful to someone 👍 

I am a bit surprised by this warning though. Apparently it seems to think that  `INFINITY` overflows on `float`. At the club we are using Clang and GCC and we never had an issue with this. Could it be an issue with MSVC ?

Are you compiling this file as a C or a C++ project if your toolchain makes a distinction between the two ?

**Comment by FrancoisCarouge** [comment]
Hi Antoine,
The Microsoft Visual Studio C/C++ compiler makes a distinction between the two. It should be compiled for a C target.

**Comment by nuft** [comment]
You need to compile for C99 / C++11 language standard or later.

**Comment by antoinealb** [comment]
Actually if you compile it in C89 it fails with an error:

```
root@53e5e973d2b7:/code# gcc -c pid.c -Wall -Wextra -std=c89
pid.c: In function 'pid_init':
pid.c:11:29: error: 'INFINITY' undeclared (first use in this function)
     pid->integrator_limit = INFINITY;
                             ^
pid.c:11:29: note: each undeclared identifier is reported only once for each function it appears in
```

@FrancoisCarouge Can you use another compiler ? Otherwise I would suggest ignoring this warning or even disabling it in your compiler options.

**Comment by FrancoisCarouge** [comment]
Yes, I am essentially ignoring this warning, we are using C++11 in the project. I'll confirm we use C99 and not 89. This compiler is very recent and I was expecting it to natively support this project. As your project grows, you will have to ensure compatibility with a wide variety of compilers, not just clang. Thank you :-D

**Comment by antoinealb** [comment]
We are aware that we need to support more than one compiler, but MSVC is very different from our targets (who have LLVM and GCC based toolchains). If you find a way to support the `INFINITY` macro in  MSVC correctly I would be happy to merge that in 😉
